### ISSUE TITLE
Why is the version info being imported through an exec?

### ISSUE THREAD

**Issue by CodyKochmann** [HypothesisWorks/hypothesis-python#1086]
I was looking through the `setup.py` and noticed that line 39 was executing the file. After taking a deeper look, this looks like this could be done with a simple import. Is there something special about this? or why isn't this an import?

https://github.com/HypothesisWorks/hypothesis-python/blob/94a720582e3bdcdd409c42f618a4073d21f93a1a/setup.py#L39

**Comment by DRMacIver** [comment]
Because this ensures that the setup.py works regardless of whether the package works. If we imported hypothesis.version we would:

1. Have to do path shenanigans to make sure that we were importing from the right place anyway (e.g. if there were already Hypothesis installed, we'd have to make sure the local version was loaded anyway)
2. Break at install time if any of our dependencies weren't yet installed, because importing `hypothesis.version` would load `hypothesis` which would break when e.g. failing to import attrs.

In contrast, using exec here is simple and works well.

[Here's a good discussion of the various trade offs between different options](https://packaging.python.org/guides/single-sourcing-package-version/).

**Comment by CodyKochmann** [comment]
I get why you're doing a relative import for the version info and find it a little surprising that there is documentation suggesting this method.

Why not just append the file to `sys.path` and import it with `from version import *` to reduce the chance of causing unpredictable behavior though?

I thought that was the whole point of being able to live edit `sys.path`.

**Comment by DRMacIver** [comment]
>  to reduce the chance of causing unpredictable behavior though?

Mutating global state to put a whole bunch of things including common names like "version" and "internal" on the import path ahead of everything else does not strike me as a good way to avoid unpredictable behaviour compared to a simple piece of code that does an obvious thing and has literally never broken for us!
