### ISSUE TITLE
integer distribution?

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis-python#1138]
Sorry about the title, but I'm unsure what to say about this. I was debugging an issue in our own code when I noted that the distribution i'm seeing from the integers strategy seems pretty wonky. If given the range [5, 6], it only chooses 6:

```
>>> s = st.integers(5, 6)
>>> Counter(tuple(s.example() for _ in range(9999)))
Counter({6: 9999})
```

If given [5, 7], it chooses 5 one fourth as any other integer:
```
>>> s
integers(min_value=5, max_value=7)
>>> Counter(tuple(s.example() for _ in range(999)))
Counter({7: 461, 6: 432, 5: 106})
>>> Counter(tuple(s.example() for _ in range(9999)))
Counter({7: 4469, 6: 4405, 5: 1125})
```

I'm running hypothesis version 3.44.26.

**Comment by Zac-HD** [comment]
Related to #909?  I suspect this has something to do with a geometric distribution - tag @DRMacIver, you're it.

**Comment by dchudz** [comment]
(I'll un-assign myself if I don't figure it out in the time I have tonight.)

**Comment by dchudz** [comment]
@bukzor I could reproduce the lack of 5's using `s.example()` like in your interactive code example, but I suspect in your actual tests you got the full range of values.

Does that sound right? If not, an example of using `@given` in a test and getting undesired behavior would be very useful.

I think what's happening is basically hypothesis's heuristics for efficiently exploring the search space are interacting with the fact that there aren't a lot of things to try: You'll see the same thing for `st.booleans()` or `st.sampled_from(['a', 'b'])`. 

(Multiple calls to `.example()` shouldn't be thought of as one long exploration of the search space -- instead, each call is independently following the same heuristics that happen to give a deterministic outcome for these examples.)

I'm uncertain whether there's any to the behavior that's worth making. The documentation for `.example` already has caveats, but maybe it should have even more.

**Comment by alexwlchan** [comment]
To add to what David said, if you try this with `@given`, you can see both values appear:

```python
from hypothesis import given
from hypothesis.strategies import integers


@given(integers(min_value=0, max_value=1))
def test_never_finds_zero(x):
    assert x > 0


@given(integers(min_value=0, max_value=1))
def test_never_finds_one(x):
    assert x < 1
```

Both tests fail for me on the first one, and further tracing suggests that because the size of the search space is less than the max_examples setting, it's an exhaustive search.

@dchudz Which part of the docs were you looking at for `<strategy>.example()`? I can't seem to find them, and I have half a memory that we don't have that warning in anything public, and resolved to fix that in the past (but never actually did so).

**Comment by dchudz** [comment]
@alexwlchan Oops, right, I see it's not in the built docs. 90% of my interaction with documentation is via `?` in ipython, so I was just looking at the docstring and stopped there:

```
        """Provide an example of the sort of value that this strategy
        generates. This is biased to be slightly simpler than is typical for
        values from this strategy, for clarity purposes.

        This method shouldn't be taken too seriously. It's here for interactive
        exploration of the API, not for any sort of real testing.

        This method is part of the public API.
```

**Comment by bukzor** [comment]
Ah, thanks everyone. In this particular application, hypothesis is used as an example-generation framework, rather than for testing, and there's an assertion that the examples span the state space.

Is there any simple way to provide something like `.example()` while providing better state-space coverage?

**Comment by DRMacIver** [comment]
>  In this particular application, hypothesis is used as an example-generation framework, rather than for testing

I'm afraid this isn't remotely a supported use case for Hypothesis.

**Comment by bukzor** [comment]
I would have guessed it's not supported. We can close this ticket as "working as intended." I'd be grateful for an answer to my question though:

> Is there any simple way to provide something like .example() while providing better state-space coverage?

**Comment by bukzor** [comment]
Could one of you give a bit more detail on how it draws only 6 in this example? The way I read the code, it should be using a legitimate random number generator for this (`new_random` called by `find` in core.py).

**Comment by dchudz** [comment]
I'm new at this, but I *think* it's because [`generate_novel_prefix`](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/engine.py#L292) only generates novel prefixes.

Also-- As David said, not supported, and I'm a little hesitant to say anything, but if you *really* want to... could you write a test that adds examples to some data structure scoped outside the test? And that way get a list of everything hypothesis looked at?

**Comment by bukzor** [comment]
Ohhh, so it's a side-effect of the skip-the-first-example behavior of `find`, yes?

**Comment by dchudz** [comment]
Yeah. (Without that, you'd just get `5` instead of just getting `6`.)

**Comment by DRMacIver** [comment]
> Is there any simple way to provide something like .example() while providing better state-space coverage?

Yes: It's to use `@given`.

Hypothesis is very heavily designed around the fact that it controls the testing loop, and that's not only not going to change it's going to get more strongly the case over time. You're essentially throwing away almost all of the benefits of using Hypothesis by trying to invoke it this way.

In general, I think what you are trying to do is very much not in Hypothesis's intended use case. I'd fairly strongly recommend not trying to contort Hypothesis into working for it, because we're not going to be at all open to changing this.
