### ISSUE TITLE
PyPI upgrades are breaking our OSX builds on CircleCI

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#1180]
See [this status page](https://status.python.org/incidents/hdx7w97m5hr8) and pypa/packaging-problems#130 - basically, we need to upgrade to pip 9.0.3 on OSX.  Given that we can't use `pip` to do this, the easiest way is probably to use Homebrew to create a fresh Python3 install - the tests themselves run under tox in pythons downloaded by the Makefile.

If any of the @HypothesisWorks/hypothesis-python-contributors use OSX, this would be a great time to step up because I have no idea how to do that.

**Comment by alexwlchan** [comment]
I use OS X, I could have a look. (Or we could just disable the Circle builds!)

**Comment by Zac-HD** [comment]
Hopefully it's an easy fix and we can just get it working again, because we make some bold claims about testing on everything - it would be a shame to take that out of the docs and we'll probably need it when we start looking at a Rust backend.

**Comment by dchudz** [comment]
Link to a failing CircleCI build in case this helps anyone: https://circleci.com/gh/HypothesisWorks/hypothesis-python/3126?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link (but it doesn't give the relevant info, for the reasons in the issue Zac linked).

**Comment by dchudz** [comment]
I'm also OSX, so I can a look if you don't, @alexwlchan.

**Comment by dchudz** [comment]
@alexwlchan @Zac-HD I don't think https://github.com/HypothesisWorks/hypothesis-python/pull/1181 fixed this.

I just got [this failure](https://circleci.com/gh/HypothesisWorks/hypothesis-python/3148?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on master after a merge, which I think has the same root cause as the earlier ones.

We shouldn't think we've fixed it until we get a CircleCI pass in the first 10 minutes of the hour.

**Comment by dchudz** [comment]
Also, until this is fixed... I guess don't merge in the first 10 minutes of the hour! 🤷‍♂️

**Comment by Zac-HD** [comment]
It's now the first 15 minutes of every half-hour - https://status.python.org/incidents/hdx7w97m5hr8 - but everything seems to be working, so I'm closing the issue again.
