### ISSUE TITLE
`strategy.choices` should support picking items from a set.

### ISSUE THREAD

**Issue by tomprince** [HypothesisWorks/hypothesis-python#221]
I'd like to write code something like

``` python
ALL = {'a', 'b', 'c'}
ALLOWED = {
    'x': {'a'},
    'y': {'a','b'},
    'z': {'a,'c'},
}

@st.given(st.sample_from(ALLOWED.keys()), st.choices())
def test(which, choice):
    disallowed = choice(ALL - ALLOWED[which])
    ...
```

**Comment by kxepal** [comment]
But choices strategy is similar to random.choice, which cannot work with sets as well...

**Comment by tomprince** [comment]
That doesn't mean that `strategy.choices` can't.

**Comment by DRMacIver** [comment]
Sorry for the delay on replying to this one too.

I'm not *intrinsically* against this, but I don't currently have good ideas about how it could be possible.

The problem is that there's no actually stable way of choosing an element from a set because sets aren't ordered. This makes things like minimization and saving of the generated examples nearly impossible to do correctly.

I'll leave this open as it's not an unreasonable thing to want, but I wouldn't hold your breath. I'd recommend using lists or other indexable sequences if you want to be able to choose from them.
