### ISSUE TITLE
Allow decorating TestCase classes (to decorate all tests in a class with a `given`)

### ISSUE THREAD

**Issue by ajtulloch** [HypothesisWorks/hypothesis-python#317]
`mock.patch` allows decorating a `TestCase` class, which decorates all tests in the class.

```
Patch can be used as a TestCase class decorator. It works by decorating each test method in the class. This reduces the boilerplate code when your test methods share a common patchings set.
```

https://docs.python.org/3/library/unittest.mock.html

This would be handy if you have multiple inputs you want to DRY amongst various test cases, e.g.

```
@given(gc=gradient_checkers(), dc=device_checkers())
class TestHypothesis(unittest.TestCase):
    @given(inputs=tensors(n=2), in_place=st.booleans())
    def test_sum(self, inputs, in_place, gc, dc): 
        ...

    @given(input=tensor())
    def test_relu(self, inputs, in_place, gc, dc): 
        ...
```

Does something like this exist in Hypothesis?

**Comment by DRMacIver** [comment]
Nothing like this currently exists.

I'm not *in principle* against the feature, but it comes with a whole bunch of weird interactions. Also unittest is pretty far from being my preferred test runner, so if something like this were possible I'd prefer a more general one that can be used without it.

Is your use case simply not repeating arguments? Would e.g. something like the following (not currently supported, just a made up approach) solve your use case just as well?

```python
base = given(gc=gradient_checkers(), dc=device_checkers())

class TestHypothesis(unittest.TestCase):
    @base.given(inputs=tensors(n=2), in_place=st.booleans())
    def test_sum(self, inputs, in_place, gc, dc): 
        ...

    @base.given(input=tensor())
    def test_relu(self, inputs, in_place, gc, dc): 
```

i.e. allowing given directions to be chained so that you can fill in some of them initially and others later.

**Comment by ajtulloch** [comment]
Yeah, chaining would be fine as well.  I'm current doing:

```
base = dict(gc=gradient_checkers(), dc=device_checkers())


@given(inputs=tensors(n=2), in_place=st.booleans(), **base)
def test_sum(...):
  ...
```

which is about the same as what you've proposed up there.

**Comment by Zac-HD** [comment]
I think this is incompatible with #958 - the interface would be inconsistent with single-`@given` on any other for of test, even if we could support it in code.
