### ISSUE TITLE
Add a dbus signature strategy to hypothesis-extra?

### ISSUE THREAD

**Issue by mulkieran** [HypothesisWorks/hypothesis-python#373]
I have such a strategy implemented and it seems to work pretty well:
https://github.com/mulkieran/hypothesis-extra-dbus-signature.

Would you be interested in a PR to add it to hypothesis extras?

**Comment by mulkieran** [comment]
@DRMacIver it has occurred to me that it probably makes just as much sense for me to keep the strategy independent of the hypothesis repo. That way the release schedule of the strategy can be iindependent of hypothesis'. I wonder if you would consider setting something up like the doc where users can add projects that are using hypothesis to the list; except this list would be of strategies instead. It seems like potentially less overhead for everybody, but realizes the goal of making publicly available strategies publicly known.

What do you think?

**Comment by DRMacIver** [comment]
Ack. Sorry, I didn't mean to ignore this.

I think the idea of having it be a separate project and having something in the documentation highlighting it is probably a good one, both for the release cycle reasons you suggest and also because it means you don't have to deal with the grief of keeping a large amount of code conforming to the slightly idiosyncratic Hypothesis style. :-)

It's up to you though. I'd be happy to include it in Hypothesis if you wanted it to be, though I don't think it fits under the extra namespace which is designed for things that require additional dependencies (which I don't think this does?).

**Comment by mulkieran** [comment]
You're quite right that it has no dependencies (other than hypothesis). I couldn't figure out a better place to put it.

But I am leaning toward the independent package with a roster in Hypothesis docs approach. It seems like it gets just about all the benefits with less work.

If you would like, I'll put together a PR for the roster similar to "docs/usage.rst". Let me know if that sounds good.

**Comment by DRMacIver** [comment]
Yup. I'd be very happy to accept such a pull request. Thanks!

Also, this work sounds interesting and I'd like to know more about how you're using it (and I think others would too). Would you maybe consider writing a guest post for hypothesis.works?

**Comment by mulkieran** [comment]
My strategy got moved to a more official place, and renamed: https://github.com/stratis-storage/hs-dbus-signature. PR coming up soon. Thanks for the offer! I'm glad you think it's interesting and look forward to coming up with some publishable insights.

**Comment by mulkieran** [comment]
PR #398. I had thought that I would end up with a few more strategies that should be published, and a list with two entries is so much more impressive than a list with one. But it turns out that the others aren't really mature enough yet, while this one is very stable, so here it is.

**Comment by mulkieran** [comment]
Resolved by #398.
