### ISSUE TITLE
Document minimal strategy API to allow custom strategies

### ISSUE THREAD

**Issue by gregory-nisbet** [HypothesisWorks/hypothesis-python#375]
I've only just started using the library so this may be impossible and/or already documented.

From reading the docs I can't seem to find the API that an object would need to conform to in order to be used as a strategy. It seems to that the combination of a generator (taking an entropy source and returning a value), a partial ordering on the values, and, optionally, a way to get a list of "adjacent" smaller values (satisfying the partial order) would be sufficient to make a strategy that behaves like the built-in ones.

For instance if you had something like, https://gist.github.com/gregory-nisbet/84146e41303495630fcf7759da10116a, is it possible to package that into a hypothesis strategy?

**Comment by alexwlchan** [comment]
You probably don’t want to be writing a strategy from scratch; there are ways to compose and combine existing strategies (and include user-defined classes) that are much simpler. This is in the [What you can generate and how](http://hypothesis.readthedocs.io/en/latest/data.html#adapting-strategies) page of the documentation.

At a quick glance, it looks like you could do something with the `recursive()` strategy. There’s an [example in the docs](http://hypothesis.readthedocs.io/en/latest/data.html#recursive-data) to build a strategy for JSON in this way.

Looking at the `make_tree()` function in your code, I think something like this would suffice for that use case:

```python
import hypothesis.strategies as st

def tree_strategy():
    return st.recursive(st.booleans(), st.lists)
```

**Comment by DRMacIver** [comment]
It's a deliberate design decision that the Hypothesis core for building a strategy isn't part of the public API, because it's prone to evolve a lot between versions and I don't want to keep the internals backwards compatible if I don't have to. The intent is that you use the composition functions in hypothesis.strategies, as per @alexwlchan's links, which are part of the stable public API.

To answer your specific question as well: No, it's not possible to package your custom shrinking into a Hypothesis strategy, but you generally shouldn't need to if you use the public API. Hypothesis doesn't support custom shrinking - the core shrinking implementation works on a lower level intermediate representation of the data, not on the values generated.
