### ISSUE TITLE
Better release automation

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#408]
The current release process is a bit mickey mouse and involves me manually running pip commands. This is less than ideal.

It should be possible to set up Travis to build packages and upload them to pypi for us whenever there is a tag that matches the version number that passes its build.

If we get this working, the next step would be to look into also building wheels - we have CI builders on Windows, OSX and Linux, and the source release should be fine for anyone on something more obscure than one of those three. This doesn't really matter now while Hypothesis is pure Python, but I'd like it to stop being pure Python at some point - there are a number of core bits it would be nice to speed up with a C extension.

**Comment by alexwlchan** [comment]
I am generally 👍 for automation.

I am also in favour of cutting a 3.7.0 release soon, because we have a bunch of cool stuff on master – in particular, all your improvements to the shrinker – that nobody else is getting to use. Why should we keep all the good stuff to ourselves?

Assuming you agree, let’s use this stone to kill one bird and maim another. You cut the 3.7.0 release, write down what you need to do, and then I’ll look at writing some automation stuff for releases.

What do you think?
