### ISSUE TITLE
Collecting custom stats

### ISSUE THREAD

**Issue by piccolbo** [HypothesisWorks/hypothesis-python#482]
This may be an  exciting new direction in which to take hypothesis or completely out of scope. I am testing some machine learning models. They are subject to old fashioned bugs but also more fuzzy failure modes such as bad performance or overfitting. Of course I can state my expectations for either as assertions, but more often I would just like to collect diagnostics to inform further actions. But a test in hypothesis can only return none, so I have to use some hacks to collect the data. I think a different use case would be performance testing. While performance may still achieve the minimum standards, I may be interested in analyzing the results. Is this something hypothesis could be reasonably extended to? What are the alternatives?

**Comment by DRMacIver** [comment]
I'm certainly not against there being functionality like this, but I think you're going to run into problems with trying to collect aggregate stats from a Hypothesis run like you want.

The problem is that Hypothesis doesn't (and never will - this is very much by design) make any guarantees about the distribution of values that it feeds you, which makes it difficult to assign much meaning to the behaviour across an entire run.

That being said, if you want to pursue the idea anyway and propose a concrete implementation and/or patch I'd be happy to provide feedback on it and help you work through the details.

**Comment by piccolbo** [comment]
That's a very good point about controlling the distribution, and you are right it makes my proposed use case downright impossible. Before we close this, for my education, could you explain why you are so adamant about not allowing any control on the data distributions? As the author of quickcheck for R, I saw data generation as an extension to the vast repertoire of distributions in R. There are default distributions for all generators, but the users can modify their parameters and even switch to different families. Hypothesis does already allow to specifiy some aspects of the distribution, for instance min  and max for numeric strategies. What it doesn't do is providing more freedom, such as switching from a uniform to a Poisson. In fact,  I had on my list of potential projects adding just this feature to numeric strategies. Of course it may very well be that I completely misunderstood quickcheck and naming my package that way was unintentionally misleading.

**Comment by DRMacIver** [comment]
>  could you explain why you are so adamant about not allowing any control on the data distributions?

Because fundamentally Hypothesis isn't about distributions, it's about adversarially generating just the right single example. Specifying the distribution would hamper its ability to do so significantly - a lot of the distributions are very heavily tweaked with a lot of heuristics rather than having any simple behaviour. The distribution will also change in the course of normal operation when e.g. shrinking a failure or replaying saved examples.

More importantly, it would greatly limit the evolution of the library - if another distribution turns out to be better at finding bugs, the correct thing to do is to switch to that, but if the distribution is part of the guarantees the library makes then you can't change it.

> Hypothesis does already allow to specifiy some aspects of the distribution, for instance min and max for numeric strategies. 

No, Hypothesis allows you to specify the *range of valid data*. This doesn't say anything about how often different examples within that range will appear. 

(There is the average\_size parameter but that was largely a mistake/workaround and will probably be deprecated at some point. Its name is also a lie and it doesn't really correspond to an average)

**Comment by piccolbo** [comment]
Not sure I completely agree but food for thought thanks.
