### ISSUE TITLE
Django builds are currently failing

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#488]
See #487 and #486 travis builds (e.g. https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/220010264#L2580).

This looks more likely to be a problem with the Hypothesis build than the actual Django integration, so it's more annoying than worrying, but obviously still important to fix!

**Comment by alexwlchan** [comment]
I point a finger in the direction of [Django 1.11](https://docs.djangoproject.com/en/1.11/releases/1.11/), which was released 4 days ago – the last passing build on master is 11 days old.

You can see in the Travis output that it’s installing Django 1.11, because we don’t pin the version in those tests.

**Comment by DRMacIver** [comment]
Fixed by #489
