### ISSUE TITLE
Use doctest to check examples in documentation are still valid

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#533]
Because it's bad when the example code doesn't actually run, eg in #320.

**Comment by DRMacIver** [comment]
I'm keen on this idea FWIW.

**Comment by Zac-HD** [comment]
Looks like [`sphinx.ext.doctest`](http://www.sphinx-doc.org/en/stable/ext/doctest.html) would be good for this.  You can provide code to insert in every example too - it's designed for imports, but we can also use it to seed the global random module on a per-block basis so that every example is independent.

- [x] initial setup, enabling ext.doctest and the seeding
- [x] change all the `code-block::` directives to `doctest::` so they're picked up
- [ ] fix all the suddenly failing examples\*
- [ ] add to build so it's checked in CI

\* working around windows shell bugs (turns out the escapes ina unicode repr break ansi handline) and flatmap examples not shrinking

**Comment by Zac-HD** [comment]
>>> rectangle_lists = integers(min_value=0, max_value=10).flatmap(
    ... lambda n: lists(lists(integers(), min_size=n, max_size=n)))
    >>> find(rectangle_lists, lambda x: len(x) >= 10)
    [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]
    # should be [[], [], [], [], [], [], [], [], [], []]
    >>> find(rectangle_lists, lambda t: sum(len(s) for s in t) >= 10)
    [[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]
    # should be [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]

We're not shrinking as well as the docs (`data.rst:229`) say we should be.

**Comment by DRMacIver** [comment]
Thanks for looking into this. ❤️ 

> We're not shrinking as well as the docs (data.rst:229) say we should be.

Interesting.

I guess I can see why that might have happened. In most ways the shrinking of flatmap has got better since that example was written, but there have been some regressions where the shape doesn't play well with the new model.

I think the first one is a genuine regression, but I'm not at all sure how to fix it. I'll open an issue though. I'd argue that the second one is an example where *both* of them are failing (the correct example is [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]] which neither are finding).

**Comment by DRMacIver** [comment]
>  there's not much to argue in favour of either of them.

Wait, no, that's not true. According to the Hypothesis size heuristics the new version *is* better, just not good enough.
