### ISSUE TITLE
Can pyup pull be automatically merged?

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#616]
Is there any reason *not* to immediately merge a pull from @pyup-bot if tests have passed?

- If so, we should document what to check or consider
- If not, we should automate it

**Comment by DRMacIver** [comment]
> Is there any reason not to immediately merge a pull from @pyup-bot if tests have passed?

Only that we don't have an immediately straightforward way to do it. It's a good idea though.

**Comment by Zac-HD** [comment]
Sounds like a job for webhooks and a bot, then 😀

**Comment by DRMacIver** [comment]
> Sounds like a job for webhooks and a bot, then 😀

A build step might be easier. We can add a github token to the encrypted files easily enough.

**Comment by Zac-HD** [comment]
A build step that doesn't run until Travis, CircleCI, and Appveyor have all passed?

**Comment by DRMacIver** [comment]
> A build step that doesn't run until Travis, CircleCI, and Appveyor have all passed?

Ah, that's a good point, I was thinking of hijacking the deploy script, but we do want to wait on Circle and Appveyor for this one too.

**Comment by Zac-HD** [comment]
This is actually pretty simply with build stages: we have the usual test stage on Travis, then two jobs in the deploy stage - the existing deployment job, and a new automerge job.  If it's a pull request by @puyp-bot, wait for Appveyor and CircleCI to finish, then merge the PR on Github (may require some admin power to do that before the deploy stage is over?).

**Comment by alexwlchan** [comment]
> wait for Appveyor and CircleCI to finish

Note that this (1) means we'd just be spinning in a Travis job for a long time, which IMO is a little wasteful of the Travis infrastructure, and (2) is prone to be flakey – jobs on Travis automatically time out after an hour. I’d more more interested in trying something with the [status webhooks on the GitHub API](https://developer.github.com/webhooks/).

(In part because something I’d like to do at the same time would be a way to comment “@magicmergebot merge this PR once the tests all pass” and walk away.)

**Comment by Zac-HD** [comment]
Per above, I do think webhooks are a better solution!  It's *possible* with build stages though 😉

**Comment by Zac-HD** [comment]
More-or-less fixed by #802
