### ISSUE TITLE
Feature request: strategies.sample() similar to random.sample()

### ISSUE THREAD

**Issue by sureshvv** [HypothesisWorks/hypothesis-python#684]
I am faking this by making several calls to strategies.choices() and removing the previously chosen element from the selection list. Can this perhaps be made easier?

**Comment by Zac-HD** [comment]
Can you post a short example or two so we can see what you're using this for?  There may be an alternative approach that avoids the problem entirely.

Otherwise, given a list `l` and sample size `k`, a sampling strategy could be written as `sets(integers(0, len(l) - 1), min_size=k, max_size=k).map(lambda s: [l[i] for i in sorted(s)])`.  This looks pretty scary on one line, but it's fairly efficient and if you're using it a few times you can define a helper function (eg `sample_list_strat(population, k)`).

**Comment by sureshvv** [comment]
``
    @rule(choice=st.choices())
    def make_forward_move(self, choice):
        persons = [x for x in self.persons if not x.crossed]
        pers1 = choice(persons)
        persons.remove(pers1)
        pers2 = choice(persons)
        sample = [pers1, pers2]

**Comment by Zac-HD** [comment]
I suggest decorating with [`@rule(data())`](https://hypothesis.readthedocs.io/en/master/data.html#hypothesis.strategies.data) and drawing from a sampled_from strategy.
