### ISSUE TITLE
Settings and profiles are not flexible enough

### ISSUE THREAD

**Issue by corehack** [HypothesisWorks/hypothesis-python#697]
I wanted to control number of examples per run. I don't like (imho) too long `--hypothesis-profile`, so I created a special profile with `max_examples = 1`. Then I tried to set it in a global fixture, but it doesn't work.
```
@pytest.fixture(autouse=True, scope='session')
def apply_cmdline_opts():
    if pytest.config.getoption("--one-example"):
        settings.load_profile('one_example')
```

Also, if I wanted to have a flexible examples control (without creating a huge mess of profiles) I couldn't do that - looks like I always have to provide exact settings at startup (import time) - I can't create profile and set it at runtime - it did not work for me.
Maybe I'm missing something (suggestions are welcome), but the current situation is a bit disappointing.

**Comment by DRMacIver** [comment]
You can certainly create a profile and setting at runtime, but your tests will use whatever the active profile was when they were defined. If you want them to do otherwise, you can use settings as a decorator to override their behaviour.

I'm happy to take specific suggestions of how you would like the settings system to be improved, but it's already extremely complicated and with a lot of non-trivial interactions, so it's not exactly going to be straightforward.

**Comment by corehack** [comment]
One idea is for `given` to work like a settings decorator, but using current profile at the time of running the test. It's not clear, what is the point of having the ability to create new profiles at runtime if tests will only use import time profile ? Being able to declare profile in the code is nice to have, sure, but sometimes it may be not enough.

**Comment by corehack** [comment]
So it could work like this: `given` wraps with settings from the "default" profile - i.e. the currently "loaded" one. Then, assuming "settings" decorator wraps the `given` and not the other way around, it could apply all non-default settings it wants.
