### ISSUE TITLE
Why is the timeout setting going away?

### ISSUE THREAD

**Issue by CodyKochmann** [HypothesisWorks/hypothesis-python#764]
Can you explain why the `timeout` setting for hypothesis is going away? I get that its a little more nondeterministic with how much will be tested but it was a really nice thing to have during development. 

Someone got me into the habit of when writing a script, just have hypothesis set to test what functions I already have written for 1-2 seconds each time I hit `build` to make sure what I've written so far is working. When I do that I can cleanly expect `number_of_functions * duration_of_each_test` in seconds to be taken to do a few more tests on my old stuff and then see if the new code will work as well. 

If this is taken away, lets say I just stick to `1000` tests per build. It would become more difficult to determine if things were running slightly faster (the timeout setting made this really easy since it was `x` number of runs happened in `y` seconds). This would also mean that for slower functions or when the test box is bogged down with other things, the settings for each function would need to be tweaked for the script to not take a long time to quick test.

I'm fine with the timeout setting going away if there's good reason/intention. `hypothesis` has absolutely been one of those libraries that seems to have a clear path in knowing where its going, I'd just like to know what the reasoning behind this change is.

```
/Users/cody/py2/lib/python2.7/site-packages/hypothesis/core.py:725: HypothesisDeprecationWarning: Your tests are hitting the settings timeout (10.00s). This functionality will go away in a future release and you should not rely on it. Instead, try setting max_examples to be some value lower than 6274 (the number of examples your test successfully ran here). Or, if you would prefer your tests to run to completion, regardless of how long they take, you can set the timeout value to hypothesis.unlimited.
```

**Comment by DRMacIver** [comment]
> Can you explain why the timeout setting for hypothesis is going away?

The big reason is that it's masking a lot of problems when people use it (and that currently *everybody* is using it by default). It makes it very easy to write tests that look like they're testing a lot more than they are, because you set a timeout at one level and then it silently degrades the quality of your testing as your test gets slower. Or even your test starts slow and looks like it's testing a lot, but in reality it's testing hardly anything because it's hitting the timeout.

Overconfidence in your testing is generally a big problem, and right now Hypothesis does too much to encourage it, so removing timeout is a way of walking that back a bit.

In general the correct thing to do is write faster tests or run fewer examples rather than just having test quality silently degrade when your tests get slow. Hypothesis should be growing a bunch of features that help with the "faster tests" aspect of it over the next half year or so, and the timeout feature won't be going away before that happens, but the early deprecation is a good way to make sure that all of the pain points that timeout is currently helping people mask are found out before it goes away.

> It would become more difficult to determine if things were running slightly faster (the timeout setting made this really easy since it was x number of runs happened in y seconds).

I don't think this is true, but maybe I'm misunderstanding what you're saying: In general the timeout makes it much harder to determine if things are running slightly faster, because it tends to result in most of your tests taking the same amount of time regardless of how fast the underlying test functions are.

**Comment by marcinpohl** [comment]
There should be a lower and upper bound for generated cases.  For example:
I want a 'minimum acceptable amount of testing' 500 tests or 0.5 sec whichever hits first. Also, I want a 'sanity check/upper limit', a maximum of 10000 tests or 7 seconds, whichever happens first. 

Those are just numbers that worked for me for many functions, they should be overwritable of course.

**Comment by Zac-HD** [comment]
> Can you explain why the timeout setting for hypothesis is going away? I get that its a little more nondeterministic with how much will be tested [...]

Per #534, that's basically it - your [battle-tested](https://github.com/CodyKochmann/battle_tested) decorator is cool, but quite unrelated to the main use-cases for Hypothesis.

@marcinpohl, we disagree here - if you specify 'at least 500 tests or 0.5 seconds' and we test one case in that time, it's a lot less testing than most users would expect.  Given the rise of shared hosts for testing, taking time out of it is the only way to make test runs reliable.
