### ISSUE TITLE
Missing Git tag for 3.18.4 release

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis-python#796]

**Comment by Zac-HD** [comment]
We also have `RELEASE.rst` in the repo, which shouldn't exist.  Proposed fix:

- @DRMacIver resolves build issues (again)
- We merge #790, which is entirely ready
- I rebase #789, which only needs the rst-lint fix, and someone merges it after review
- I rebase #791. which I'm pretty sure is working but hasn't run tests for a while, and hopefully it's mergeable too

**Comment by DRMacIver** [comment]
OK. I have manually(ish) created a tag for 3.18.4 and hopefully fixed our build issues. I think @Zac-HD's plan is good for debugging that.

I've also swapped the order on the build so that we deploy to pypi after fixing the tag. As it happens that *wouldn't* have fixed this particular screwup, but it should make this general category of problems less likely.
