### ISSUE TITLE
Question: why was SQLite examples database deprecated?

### ISSUE THREAD

**Issue by jwg4** [HypothesisWorks/hypothesis-python#979]
Hi there,

I couldn't find a previous PR discussion or issue so I thought I would just ask: what was the reason that the SQLite database is no longer used? An implementation problem or just a decision that it wasn't the right solution?

I have no particular axe to grind - I'm just interested in SQLite (and Hypothesis)

Thanks!

**Comment by DRMacIver** [comment]
Just that it wasn't the right solution - the nice property of the newer on disk format for the example database is that it is automatically mergeable - you can check it into version control and merges will always resolve correctly (because it never has to do a merge at the file level). Unsurprisingly, sqlite doesn't have this property!

There's nothing intrinsically wrong with sqlite other than that, it just doesn't have any advantages for our purposes and isn't available on all Python platforms, so there isn't any reason to continue to support it.

**Comment by jwg4** [comment]
The version control reason makes a lot of sense. Thanks for the informative and speedy response!
